// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: handbooks.proto

package content_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Handbook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug        string `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Lang        string `protobuf:"bytes,4,opt,name=lang,proto3" json:"lang,omitempty"`
	UrlLink     string `protobuf:"bytes,5,opt,name=url_link,json=urlLink,proto3" json:"url_link,omitempty"`
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Active      bool   `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt   string `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   string `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Date        string `protobuf:"bytes,10,opt,name=date,proto3" json:"date,omitempty"`
	AccessType  string `protobuf:"bytes,11,opt,name=access_type,json=accessType,proto3" json:"access_type,omitempty"`
}

func (x *Handbook) Reset() {
	*x = Handbook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handbooks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Handbook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handbook) ProtoMessage() {}

func (x *Handbook) ProtoReflect() protoreflect.Message {
	mi := &file_handbooks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handbook.ProtoReflect.Descriptor instead.
func (*Handbook) Descriptor() ([]byte, []int) {
	return file_handbooks_proto_rawDescGZIP(), []int{0}
}

func (x *Handbook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Handbook) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Handbook) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Handbook) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *Handbook) GetUrlLink() string {
	if x != nil {
		return x.UrlLink
	}
	return ""
}

func (x *Handbook) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Handbook) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Handbook) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Handbook) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Handbook) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Handbook) GetAccessType() string {
	if x != nil {
		return x.AccessType
	}
	return ""
}

type GetOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetOneRequest) Reset() {
	*x = GetOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handbooks_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneRequest) ProtoMessage() {}

func (x *GetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_handbooks_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneRequest.ProtoReflect.Descriptor instead.
func (*GetOneRequest) Descriptor() ([]byte, []int) {
	return file_handbooks_proto_rawDescGZIP(), []int{1}
}

func (x *GetOneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOneHandbookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug        string `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Lang        string `protobuf:"bytes,4,opt,name=lang,proto3" json:"lang,omitempty"`
	UrlLink     string `protobuf:"bytes,5,opt,name=url_link,json=urlLink,proto3" json:"url_link,omitempty"`
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Active      bool   `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt   string `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *GetOneHandbookResponse) Reset() {
	*x = GetOneHandbookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handbooks_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneHandbookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneHandbookResponse) ProtoMessage() {}

func (x *GetOneHandbookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_handbooks_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneHandbookResponse.ProtoReflect.Descriptor instead.
func (*GetOneHandbookResponse) Descriptor() ([]byte, []int) {
	return file_handbooks_proto_rawDescGZIP(), []int{2}
}

func (x *GetOneHandbookResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOneHandbookResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetOneHandbookResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *GetOneHandbookResponse) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *GetOneHandbookResponse) GetUrlLink() string {
	if x != nil {
		return x.UrlLink
	}
	return ""
}

func (x *GetOneHandbookResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetOneHandbookResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *GetOneHandbookResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetHandbooksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit   uint32            `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page    uint32            `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Options map[string]string `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetHandbooksRequest) Reset() {
	*x = GetHandbooksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handbooks_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHandbooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHandbooksRequest) ProtoMessage() {}

func (x *GetHandbooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_handbooks_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHandbooksRequest.ProtoReflect.Descriptor instead.
func (*GetHandbooksRequest) Descriptor() ([]byte, []int) {
	return file_handbooks_proto_rawDescGZIP(), []int{3}
}

func (x *GetHandbooksRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetHandbooksRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetHandbooksRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetHandbooksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count     uint32      `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Handbooks []*Handbook `protobuf:"bytes,2,rep,name=handbooks,proto3" json:"handbooks,omitempty"`
}

func (x *GetHandbooksResponse) Reset() {
	*x = GetHandbooksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handbooks_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHandbooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHandbooksResponse) ProtoMessage() {}

func (x *GetHandbooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_handbooks_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHandbooksResponse.ProtoReflect.Descriptor instead.
func (*GetHandbooksResponse) Descriptor() ([]byte, []int) {
	return file_handbooks_proto_rawDescGZIP(), []int{4}
}

func (x *GetHandbooksResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetHandbooksResponse) GetHandbooks() []*Handbook {
	if x != nil {
		return x.Handbooks
	}
	return nil
}

var File_handbooks_proto protoreflect.FileDescriptor

var file_handbooks_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x68, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xa0, 0x02, 0x0a, 0x08, 0x48,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x72, 0x6c, 0x5f, 0x6c, 0x69, 0x6e,
	0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x72, 0x6c, 0x4c, 0x69, 0x6e, 0x6b,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x22, 0x1f, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xda,
	0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x6f,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x6c, 0x75, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x72, 0x6c, 0x5f, 0x6c,
	0x69, 0x6e, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x72, 0x6c, 0x4c, 0x69,
	0x6e, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xc0, 0x01, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x43, 0x0a,
	0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x5d,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x09,
	0x68, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x6f, 0x6b, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x42, 0x1a, 0x5a,
	0x18, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_handbooks_proto_rawDescOnce sync.Once
	file_handbooks_proto_rawDescData = file_handbooks_proto_rawDesc
)

func file_handbooks_proto_rawDescGZIP() []byte {
	file_handbooks_proto_rawDescOnce.Do(func() {
		file_handbooks_proto_rawDescData = protoimpl.X.CompressGZIP(file_handbooks_proto_rawDescData)
	})
	return file_handbooks_proto_rawDescData
}

var file_handbooks_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_handbooks_proto_goTypes = []interface{}{
	(*Handbook)(nil),               // 0: content.Handbook
	(*GetOneRequest)(nil),          // 1: content.GetOneRequest
	(*GetOneHandbookResponse)(nil), // 2: content.GetOneHandbookResponse
	(*GetHandbooksRequest)(nil),    // 3: content.GetHandbooksRequest
	(*GetHandbooksResponse)(nil),   // 4: content.GetHandbooksResponse
	nil,                            // 5: content.GetHandbooksRequest.OptionsEntry
}
var file_handbooks_proto_depIdxs = []int32{
	5, // 0: content.GetHandbooksRequest.options:type_name -> content.GetHandbooksRequest.OptionsEntry
	0, // 1: content.GetHandbooksResponse.handbooks:type_name -> content.Handbook
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_handbooks_proto_init() }
func file_handbooks_proto_init() {
	if File_handbooks_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_handbooks_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Handbook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_handbooks_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_handbooks_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneHandbookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_handbooks_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHandbooksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_handbooks_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHandbooksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_handbooks_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_handbooks_proto_goTypes,
		DependencyIndexes: file_handbooks_proto_depIdxs,
		MessageInfos:      file_handbooks_proto_msgTypes,
	}.Build()
	File_handbooks_proto = out.File
	file_handbooks_proto_rawDesc = nil
	file_handbooks_proto_goTypes = nil
	file_handbooks_proto_depIdxs = nil
}
